name: PR Build and Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/radius_clustering/**"
      - "tests/**"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  run_pytest:
        name: Run pytest
        uses: ./.github/workflows/tests.yml

  build_test_sdist:
    name: Test source distribution
    runs-on: self-hosted
    needs: run_pytest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build sdist
        run: |
          pip install --upgrade pip
          pip install pipx
          pipx run build --sdist

      - name: Test sdist
        run: |
          pip install ./dist/*.tar.gz
          python -c "import radius_clustering; print(f'Successfully imported version {radius_clustering.__version__}')"